[package]
authors = ["SchweGELBin <schwegelbin@gmail.com>"]
edition = "2024"
name = "mixbot"
version = "0.2.2"


[dependencies]
anyhow = "^1.0"
azalea = "^0.13"
parking_lot = "^0.12"
poise = "^0.6"
tokio = { version = "^1.46", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "^0.3"
